### ISSUE TITLE
setAuthorizationHeaderFieldWithCredential: produces wrong header

### ISSUE THREAD

**Issue by rajderks** [AFNetworking/AFOAuth2Manager#117]
(talking about the 3.0.0. branch here)

When using setAuthorizationHeaderFieldWithCredential: the library produces the following header field

`Authorization = "Basic <wrong token here>";`

To my knowledge, it should be
`Authorization = "Bearer <token here>";`

Also, the token in the 'Basic' case is NOT the access token stored in the AFOAuthCredential for given provider identifier.

When setting the Authorization header myself with the bearer keyword and my valid access token the call works.

**Comment by buranmert** [comment]
Commit: cafa193c4270ead808d976a28285e0bf887dcae0

Inside `AFOAuth2Manager`'s designated initializer method:

``` objective-c
- (id)initWithBaseURL:(NSURL *)url
 sessionConfiguration:(NSURLSessionConfiguration *)configuration
             clientID:(NSString *)clientID
               secret:(NSString *)secret {
    ...
    self.useHTTPBasicAuthentication = YES;
    ...
}
- (void)setUseHTTPBasicAuthentication:(BOOL)useHTTPBasicAuthentication {
    _useHTTPBasicAuthentication = useHTTPBasicAuthentication;

    if (self.useHTTPBasicAuthentication) {
        [self.requestSerializer setAuthorizationHeaderFieldWithUsername:self.clientID password:self.secret];
        } else {
            [self.requestSerializer setValue:nil forHTTPHeaderField:@"Authorization"];
        }
    }
}

```

So this is automatically done:

> Authorization = "Basic <wrong token here>";

When you call `setAuthorizationHeaderFieldWithCredential:` method, your credential must pass an `if` clause to turn your HTTP header field into `Authorization = "Bearer <token here>";` which is:

``` objective-c
- (void)setAuthorizationHeaderFieldWithCredential:(AFOAuthCredential *)credential {
    if ([credential.tokenType compare:@"Bearer" options:NSCaseInsensitiveSearch] == NSOrderedSame) {
        [self setValue:[NSString stringWithFormat:@"Bearer %@", credential.accessToken] forHTTPHeaderField:@"Authorization"];
    }
}
```

Are you sure your `credential`'s `tokenType` is `Bearer`?
