### ISSUE TITLE
Please publicly expose expiration on AFOAuthCredential

### ISSUE THREAD

**Issue by mattgalloway** [AFNetworking/AFOAuth2Manager#46]
I'd like to be able to test how soon a credential will expire - not just if it has expired. This can easily be done if expiration is exposed publicly as a readonly property on AFOAuthCredential by adding 

@property (readonly, nonatomic) NSDate *expiration;

to the AFOAuthCredential interface in AFOAuth2Client.h.

Thanks,

M.

**Comment by wlisac** [comment]
@kcharwood I'd also really appreciate this being public. I'm comparing two credentials and the expiration date is important.

Re-declaration would work, but I'd prefer to avoid that in case the property name changes internally in the future.

**Comment by jameshays** [comment]
Would a category work?

**Comment by wlisac** [comment]
>  add it in a re-declaration of the @interface

I think a category is what is being proposed here.

It has the same risks I outlined above.
