### ISSUE TITLE
"AFJSONRequestOperation.h" File Not Found

### ISSUE THREAD

**Issue by jdgriffith** [AFNetworking/AFOAuth2Manager#58]
I am using cocoapods to install AFNetworking and your extension. When trying to compile I am getting the error that it can't find AFJsonRequestOperation.h. It is not clear where this dependency is or if another pod or extension should be installed. Can you advise?

**Comment by faiza-nawaz-confiz** [comment]
So, is there any alternative for this?? what's the solution
Thanks in anticipation

**Comment by djmadcat** [comment]
@faiza-nawaz-confiz migrate from AFOAuth2Client v1.x (based on AFN v1.x) to AFOAuth2Manager v2.x (based on AFN v2.x).
