### ISSUE TITLE
Client credentials are included in the request body [NOT RECOMMENDED]

### ISSUE THREAD

**Issue by samskiter** [AFNetworking/AFOAuth2Manager#85]
i've brought this up before:

>Including the client credentials in the request body using the two
parameters is NOT RECOMMENDED, and SHOULD be limited to clients
unable to directly utilize the HTTP Basic authentication scheme (or
other password-based HTTP authentication schemes).  The parameters
can only be transmitted in the request body and MUST NOT be included
in the request URI.

AFNetworking already supports basic auth headers so this shouldn't be hard to change.

**Comment by mattt** [comment]
Fixed by 412d256.
