### ISSUE TITLE
Problem with cocoapods 0.36 use_framework!

### ISSUE THREAD

**Issue by zixsma** [AFNetworking/AFOAuth2Manager#91]
After update cocoapods to version 0.36 and use Framework. I found that AFOauth2Manager cannot import AFNetworking library to use in code. Xcode show error in AFOauth2Manager code where import AFNetworking code.

**Comment by andresbrun** [comment]
Same here with 0.37.

**Comment by jadidian** [comment]
Same here, AFOAuth2Manager and `use_framework!` don't work together, I spent hours trying different config / header search paths / framework search paths without success.

**Comment by ryanmaxwell** [comment]
yep this is making it difficult to use in swift

**Comment by juanuribeo13** [comment]
I fixed this by changing the following imports

- `#import "AFURLRequestSerialization.h"`
- `#import "AFHTTPRequestOperationManager.h"`

to

- `#import <AFNetworking/AFURLRequestSerialization.h>`
- `#import <AFNetworking/AFHTTPRequestOperationManager.h>`

This pull request fixes the problem https://github.com/AFNetworking/AFOAuth2Manager/pull/100/

**Comment by zixsma** [comment]
Thank you very much @juanuribeo13 .

**Comment by grnbeagle** [comment]
:+1:

**Comment by GregPrice24** [comment]
:+1:

**Comment by eriksundin** [comment]
+1

**Comment by kcharwood** [comment]
I've merged in the change

**Comment by sergii-frost** [comment]
Hi, I've faced this issue when using latest available release (`2.2.0`). Could you please release version with this fix?
