### ISSUE TITLE
Any chance of documenting this working with AFHTTPSessionManager?

### ISSUE THREAD

**Issue by r3mus** [AFNetworking/AFOAuth2Manager#93]
Your best practice guide for iOS 8 indicates that AFHTTPSessionManager is the way to go. Do yo have a working example of AFOAuth2Manager working with AFHTTPSessionManager?

**Comment by mattt** [comment]
I don't know what best practice guide you're referring to, but the README provides basic instructions on how AFOAuth2Manager and AFHTTPSessionManager inter-operate. Beyond that, no example project is provided.

**Comment by r3mus** [comment]
Guide: http://cocoadocs.org/docsets/AFNetworking/2.0.2/Classes/AFHTTPSessionManager.html (under subclassing notes)

What I'm referring to specifically is SessionManager has no method in its requestSerializer for `setAuthorizationHeaderFieldWithCredential:credential]`.

**Comment by samskiter** [comment]
It's provided in a category: https://github.com/AFNetworking/AFOAuth2Manager/blob/master/AFOAuth2Manager/AFHTTPRequestSerializer%2BOAuth2.m

**Comment by r3mus** [comment]
Hot! Thanks Sam.
