### ISSUE TITLE
Remove NSLogs 

### ISSUE THREAD

**Issue by merkury** [AFNetworking/AFOAuth2Manager#97]
Is it please possible to remove the NSLogs in the AFOAuth2Mangaer.m ?
It logs the identifier of the keychain entry.  This can be used by other apps to get the credentials.

Regards David

**Comment by merkury** [comment]
For me this is a serious security issue and should be fixed soon. Just removing the NSLog statements from AFOAuth2Manager.m will fix it.

**Comment by svenmuennich** [comment]
:+1:

I totally agree. It is also bit annoying during development, e.g. when checking if a credential is already stored in a shared keychain.

**Comment by svenmuennich** [comment]
I just created PR #99 that removes all `NSLog` calls.

**Comment by kcharwood** [comment]
Merged
